version: '3.7'

services:
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: movies
            MONGO_INITDB_ROOT_PASSWORD: movies2022
        ports:
            - 27017:27017
        networks:
            - app-network

    db-admin:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - db
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo-server
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: queue
            ME_CONFIG_MONGODB_ADMINUSERNAME: movies
            ME_CONFIG_MONGODB_ADMINPASSWORD: movies2022
            # ME_CONFIG_MONGODB_SERVER: db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge